//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE.ModelosIII.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BE.ModelosIII.Resources.ReportMessages", typeof(ReportMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        public static string MostSoldHourChartLabel {
            get {
                return ResourceManager.GetString("MostSoldHourChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios más vendidos para {0}, desde {1} y hasta {2}..
        /// </summary>
        public static string MostSoldHourDescription {
            get {
                return ResourceManager.GetString("MostSoldHourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios más vendidos.
        /// </summary>
        public static string MostSoldHourTitle {
            get {
                return ResourceManager.GetString("MostSoldHourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Películas más vendidas.
        /// </summary>
        public static string MostSoldMovieChartLabel {
            get {
                return ResourceManager.GetString("MostSoldMovieChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Películas más vendidas para {0}, desde {1} y hasta {2}..
        /// </summary>
        public static string MostSoldMovieDescription {
            get {
                return ResourceManager.GetString("MostSoldMovieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Películas más vendidas.
        /// </summary>
        public static string MostSoldMovieTitle {
            get {
                return ResourceManager.GetString("MostSoldMovieTitle", resourceCulture);
            }
        }
    }
}
